# Generated by Django 6.0.7 on 2026-07-21 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contingent_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('retirement_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Ledger',
                'verbose_name_plural': 'Ledgers',
            },
        ),
        migrations.CreateModel(
            name='ReservedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_reference', models.CharField(max_length=255, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_code', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_accounts', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Reserved Account',
                'verbose_name_plural': 'Reserved Accounts',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('monnify_payment_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('txn_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('split_40', '40% Contingent Split'), ('split_60', '60% Retirement Split'), ('pfa_transfer', 'PFA Transfer')], max_length=20)),
                ('wallet_type', models.CharField(blank=True, choices=[('contingent', 'Contingent (40%)'), ('retirement', 'Retirement (60%)')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
