# Generated by Django 6.0.7 on 2026-07-29 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_bmoni_user_id_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAudit',
            fields=[
                ('tx_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contingent_credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('retirement_credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bmoni_tx_id_1', models.CharField(blank=True, max_length=255, null=True)),
                ('bmoni_tx_id_2', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_audits', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Transaction Audit',
                'verbose_name_plural': 'Transaction Audits',
                'ordering': ['-created_at'],
            },
        ),
    ]
