# Generated by Django 6.0.7 on 2026-07-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transactionaudit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='monnify_payment_ref',
        ),
        migrations.DeleteModel(
            name='ReservedAccount',
        ),
    ]
