# Generated by Django 6.0.7 on 2026-07-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_transaction_monnify_payment_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionaudit',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('PENDING_SETTLEMENT', 'Recorded - BMONI settlement pending'), ('FAILED', 'Failed')], default='INITIATED', max_length=20),
        ),
    ]
