# Generated by Django 6.0.7 on 2026-07-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bmoni_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contingent_smart_wallet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contingent_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('USER_CREATED', 'User Created'), ('WALLETS_PROVISIONED', 'Wallets Provisioned'), ('KYC_COMPLETED', 'KYC Completed'), ('ACTIVE', 'Active')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='retirement_smart_wallet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='retirement_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
