# Generated by Django 6.0.7 on 2026-07-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_bmoni_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='income_type',
            field=models.CharField(choices=[('MARKET_SELLER', 'Market Trader / Cash Sales'), ('DAILY_DRIVER', 'Daily Driver / Transport'), ('FREELANCER_USD', 'Online Freelancer / USD'), ('SALARIED', 'Salaried Employee'), ('MIXED', 'Mixed Income')], default='MARKET_SELLER', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira (NGN/CNGN)'), ('USD', 'US Dollar (USD/USDB)')], default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='savings_strategy',
            field=models.CharField(choices=[('SPLIT_40_60', '40/60 Pension Split'), ('PERCENTAGE_20_80', '20% Future / 80% Available'), ('CUSTOM', 'Custom Strategy')], default='SPLIT_40_60', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usdb_smart_wallet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usdb_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
