# Generated by Django 5.2.16 on 2026-07-30 00:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('nin_bvn', models.CharField(blank=True, default='', max_length=32)),
                ('preferred_pfa', models.CharField(blank=True, default='', max_length=255)),
                ('preferred_language', models.CharField(choices=[('ENGLISH', 'English'), ('YORUBA', 'Yoruba'), ('HAUSA', 'Hausa'), ('IGBO', 'Igbo'), ('PIDGIN', 'Pidgin')], default='ENGLISH', max_length=16)),
                ('onboarding_stage', models.CharField(choices=[('NEW', 'New'), ('ASK_NAME', 'Awaiting name'), ('ASK_EMAIL', 'Awaiting email'), ('ASK_NIN', 'Awaiting NIN/BVN'), ('ASK_PFA', 'Awaiting preferred PFA'), ('ASK_LANGUAGE', 'Awaiting preferred language'), ('PROVISIONING', 'Registering with BMONI'), ('ONBOARDED', 'Fully onboarded')], default='NEW', max_length=20)),
                ('kyc_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20)),
                ('bmoni_user_id', models.CharField(blank=True, default='', max_length=128)),
                ('contingent_wallet_id', models.CharField(blank=True, default='', max_length=128)),
                ('retirement_wallet_id', models.CharField(blank=True, default='', max_length=128)),
                ('rsa_pin', models.CharField(blank=True, default='', max_length=64)),
                ('contingent_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('retirement_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tx_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contingent_credit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('retirement_credit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source', models.CharField(choices=[('VOICE_NOTE', 'Voice note'), ('TEXT', 'Text message'), ('ROUNDUP', 'Transaction round-up'), ('EOD_SWEEP', 'End-of-day sweep')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('raw_transcript', models.TextField(blank=True, default='')),
                ('intent_confidence', models.FloatField(blank=True, null=True)),
                ('bmoni_transfer_ref', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bot.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=32)),
                ('body', models.TextField(blank=True, default='')),
                ('media_url', models.URLField(blank=True, default='')),
                ('media_content_type', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_messages', to='bot.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
