# Generated by Django 6.0.7 on 2026-07-30 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_bmoni_user_id_and_more'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('preferred_pfa', models.CharField(blank=True, default='', max_length=255)),
                ('preferred_language', models.CharField(default='en', max_length=20)),
                ('stage', models.CharField(choices=[('NEW', 'New'), ('ASK_NAME', 'Awaiting name'), ('ASK_EMAIL', 'Awaiting email'), ('ASK_PFA', 'Awaiting preferred PFA'), ('ASK_LANGUAGE', 'Awaiting preferred language'), ('PROVISIONING', 'Registering with BMONI'), ('COMPLETED', 'Fully onboarded')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inboundmessagelog',
            name='user',
        ),
        migrations.AddField(
            model_name='inboundmessagelog',
            name='message_sid',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inboundmessagelog',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inboundmessagelog',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='inboundmessagelog',
            name='media_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='WhatsAppPendingTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=32)),
                ('intent', models.CharField(default='move_money', max_length=50)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contingent_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('retirement_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('raw_transcript', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=0.9)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed & Executed'), ('CANCELLED', 'Cancelled by User'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('bmoni_tx_ref', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_pending_txns', to='accounts.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
