# Generated by Django 6.0.7 on 2026-07-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BmoniApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BMONI API Call Log',
                'verbose_name_plural': 'BMONI API Call Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
